import { toPoints } from '@biz-checks/domain';

import { Stocks } from './stocks.js';

import type { CanvasObject, CanvasObjectId } from '@biz-checks/domain';

const inch = (n: number) => toPoints(n, 'inch');

const id = (suffix: string): CanvasObjectId => `obj_blueprint_${suffix}` as CanvasObjectId;

/**
 * The canonical placement of objects on a US business check, per ANSI
 * X9.100. Coordinates are relative to the check's top-left corner.
 *
 *   - Date in upper-right
 *   - Pay-to-the-order-of line in upper-left third
 *   - Numeric amount box in upper-right third
 *   - Written amount line spanning the middle
 *   - Memo line in the lower-left
 *   - Signature line in the lower-right
 *   - MICR line on the bottom 5/8" clear band
 *
 * Width 8.5" × height 3.5" — matches Stocks['business-3up'].
 */
export const StandardBusinessCheckObjects: CanvasObject[] = [
  // Company name & address (top-left header block)
  {
    id: id('company-name'),
    kind: 'text',
    name: 'Company Name',
    position: { x: inch(0.4), y: inch(0.25) },
    size: { width: inch(3.5), height: inch(0.3) },
    rotation: 0,
    locked: false,
    visible: true,
    zIndex: 1,
    value: { kind: 'literal', text: 'Your Company, Inc.' },
    fontFamily: 'Inter',
    fontSize: 14,
    fontWeight: 'bold',
    italic: false,
    underline: false,
    color: '#000000',
    justification: 'left',
    lineHeight: 1.2,
    letterSpacing: 0,
  },
  {
    id: id('company-address'),
    kind: 'text',
    name: 'Company Address',
    position: { x: inch(0.4), y: inch(0.55) },
    size: { width: inch(3.5), height: inch(0.6) },
    rotation: 0,
    locked: false,
    visible: true,
    zIndex: 1,
    value: { kind: 'literal', text: '123 Example St.\nCity, State 00000\n(555) 555-0100' },
    fontFamily: 'Inter',
    fontSize: 9,
    fontWeight: 'regular',
    italic: false,
    underline: false,
    color: '#000000',
    justification: 'left',
    lineHeight: 1.3,
    letterSpacing: 0,
  },
  // Bank name & address (top-center)
  {
    id: id('bank-name'),
    kind: 'text',
    name: 'Bank Name',
    position: { x: inch(4.4), y: inch(0.25) },
    size: { width: inch(2.5), height: inch(0.3) },
    rotation: 0,
    locked: false,
    visible: true,
    zIndex: 1,
    value: { kind: 'literal', text: 'Bank Name' },
    fontFamily: 'Inter',
    fontSize: 11,
    fontWeight: 'semibold',
    italic: false,
    underline: false,
    color: '#000000',
    justification: 'left',
    lineHeight: 1.2,
    letterSpacing: 0,
  },
  // Check number (top-right)
  {
    id: id('check-number'),
    kind: 'text',
    name: 'Check Number',
    position: { x: inch(7.0), y: inch(0.25) },
    size: { width: inch(1.3), height: inch(0.3) },
    rotation: 0,
    locked: false,
    visible: true,
    zIndex: 1,
    value: { kind: 'formula', formula: 'LabelField("SerialNumber")' },
    fontFamily: 'Inter',
    fontSize: 14,
    fontWeight: 'bold',
    italic: false,
    underline: false,
    color: '#000000',
    justification: 'right',
    lineHeight: 1.2,
    letterSpacing: 0,
  },
  // Date label & value
  {
    id: id('date-label'),
    kind: 'text',
    name: 'Date Label',
    position: { x: inch(5.7), y: inch(0.95) },
    size: { width: inch(0.5), height: inch(0.25) },
    rotation: 0,
    locked: false,
    visible: true,
    zIndex: 1,
    value: { kind: 'literal', text: 'DATE' },
    fontFamily: 'Inter',
    fontSize: 8,
    fontWeight: 'medium',
    italic: false,
    underline: false,
    color: '#444444',
    justification: 'left',
    lineHeight: 1.2,
    letterSpacing: 1,
  },
  {
    id: id('date-value'),
    kind: 'text',
    name: 'Date Value',
    position: { x: inch(6.2), y: inch(0.95) },
    size: { width: inch(2.0), height: inch(0.25) },
    rotation: 0,
    locked: false,
    visible: true,
    zIndex: 1,
    value: { kind: 'formula', formula: 'Date()' },
    fontFamily: 'Inter',
    fontSize: 11,
    fontWeight: 'regular',
    italic: false,
    underline: false,
    color: '#000000',
    justification: 'left',
    lineHeight: 1.2,
    letterSpacing: 0,
  },
  // Pay to the order of
  {
    id: id('pay-to-label'),
    kind: 'text',
    name: 'Pay To Label',
    position: { x: inch(0.4), y: inch(1.35) },
    size: { width: inch(1.5), height: inch(0.3) },
    rotation: 0,
    locked: false,
    visible: true,
    zIndex: 1,
    value: { kind: 'literal', text: 'PAY TO THE\nORDER OF' },
    fontFamily: 'Inter',
    fontSize: 8,
    fontWeight: 'medium',
    italic: false,
    underline: false,
    color: '#444444',
    justification: 'left',
    lineHeight: 1.2,
    letterSpacing: 1,
  },
  {
    id: id('payee-name'),
    kind: 'text',
    name: 'Payee',
    position: { x: inch(1.6), y: inch(1.4) },
    size: { width: inch(4.6), height: inch(0.3) },
    rotation: 0,
    locked: false,
    visible: true,
    zIndex: 1,
    value: { kind: 'label-field', field: 'Payee' },
    fontFamily: 'Inter',
    fontSize: 13,
    fontWeight: 'regular',
    italic: false,
    underline: false,
    color: '#000000',
    justification: 'left',
    lineHeight: 1.2,
    letterSpacing: 0,
  },
  // Amount box (numeric)
  {
    id: id('amount-box'),
    kind: 'amount-box',
    name: 'Amount Box',
    position: { x: inch(6.4), y: inch(1.4) },
    size: { width: inch(1.7), height: inch(0.35) },
    rotation: 0,
    locked: false,
    visible: true,
    zIndex: 1,
    value: { kind: 'label-field', field: 'Amount' },
    fontFamily: 'Inter',
    fontSize: 14,
    fontWeight: 'bold',
    color: '#000000',
    justification: 'right',
    securityFont: 'amount-protect',
    showCurrencySymbol: true,
  },
  // Written amount line
  {
    id: id('amount-words'),
    kind: 'text',
    name: 'Amount in Words',
    position: { x: inch(0.4), y: inch(1.85) },
    size: { width: inch(6.2), height: inch(0.3) },
    rotation: 0,
    locked: false,
    visible: true,
    zIndex: 1,
    value: { kind: 'label-field', field: 'AmountWords' },
    fontFamily: 'Inter',
    fontSize: 11,
    fontWeight: 'regular',
    italic: false,
    underline: false,
    color: '#000000',
    justification: 'left',
    lineHeight: 1.2,
    letterSpacing: 0,
  },
  {
    id: id('dollars-label'),
    kind: 'text',
    name: 'Dollars Label',
    position: { x: inch(6.7), y: inch(1.9) },
    size: { width: inch(1.3), height: inch(0.25) },
    rotation: 0,
    locked: false,
    visible: true,
    zIndex: 1,
    value: { kind: 'literal', text: 'DOLLARS' },
    fontFamily: 'Inter',
    fontSize: 9,
    fontWeight: 'medium',
    italic: false,
    underline: false,
    color: '#444444',
    justification: 'right',
    lineHeight: 1.2,
    letterSpacing: 1,
  },
  // Memo & signature lines
  {
    id: id('memo-label'),
    kind: 'text',
    name: 'Memo Label',
    position: { x: inch(0.4), y: inch(2.6) },
    size: { width: inch(0.5), height: inch(0.25) },
    rotation: 0,
    locked: false,
    visible: true,
    zIndex: 1,
    value: { kind: 'literal', text: 'MEMO' },
    fontFamily: 'Inter',
    fontSize: 8,
    fontWeight: 'medium',
    italic: false,
    underline: false,
    color: '#444444',
    justification: 'left',
    lineHeight: 1.2,
    letterSpacing: 1,
  },
  {
    id: id('memo-value'),
    kind: 'text',
    name: 'Memo',
    position: { x: inch(0.95), y: inch(2.6) },
    size: { width: inch(3.5), height: inch(0.25) },
    rotation: 0,
    locked: false,
    visible: true,
    zIndex: 1,
    value: { kind: 'label-field', field: 'Memo' },
    fontFamily: 'Inter',
    fontSize: 11,
    fontWeight: 'regular',
    italic: false,
    underline: false,
    color: '#000000',
    justification: 'left',
    lineHeight: 1.2,
    letterSpacing: 0,
  },
  // Memo line
  {
    id: id('memo-line'),
    kind: 'shape',
    name: 'Memo Line',
    position: { x: inch(0.95), y: inch(2.85) },
    size: { width: inch(3.5), height: 1 },
    rotation: 0,
    locked: false,
    visible: true,
    zIndex: 0,
    shape: 'line',
    strokeColor: '#000000',
    strokeWidth: 1,
    cornerRadius: 0,
  },
  // Signature line
  {
    id: id('signature-line'),
    kind: 'shape',
    name: 'Signature Line',
    position: { x: inch(5.0), y: inch(2.85) },
    size: { width: inch(3.0), height: 1 },
    rotation: 0,
    locked: false,
    visible: true,
    zIndex: 0,
    shape: 'line',
    strokeColor: '#000000',
    strokeWidth: 1,
    cornerRadius: 0,
  },
  // MICR line — placed in the 5/8" clear band per ANSI X9.100
  {
    id: id('micr'),
    kind: 'micr',
    name: 'MICR Line',
    position: { x: inch(0.5), y: inch(3.05) },
    size: { width: inch(7.5), height: inch(0.3) },
    rotation: 0,
    locked: false,
    visible: true,
    zIndex: 5,
    value: { kind: 'literal', text: '' },
    fontVariant: 'e13b',
    fontSize: 12,
    color: '#000000',
    justification: 'left',
  },
];

/**
 * Default 3-per-page business-check template (objects only). Compose with
 * a `Stocks['business-3up']` stock to form a complete `CheckTemplate`.
 */
export const StandardBusinessCheckTemplate = {
  stock: Stocks['business-3up'],
  objects: StandardBusinessCheckObjects,
} as const;
