/**
 * Browser-side template blueprints. These mirror the canonical layouts in
 * @biz-checks/check-engine but are duplicated here to keep the engine off
 * the client bundle. The shapes match `TemplateDocument` exactly.
 */

import type { CanvasObject, CheckStock, LabelField, TemplateDocument } from '@/lib/api/types';

const POINTS_PER_INCH = 72;
const inch = (n: number): number => n * POINTS_PER_INCH;

const LETTER: CheckStock['paperSize'] = 'Letter';

export const Stocks: Record<string, CheckStock> = {
  'business-3up': {
    type: 'three-per-page',
    paperSize: LETTER,
    rows: 3,
    columns: 1,
    margins: { top: 0, right: 0, bottom: 0, left: 0 },
    spacing: { horizontal: 0, vertical: 0 },
    checkSize: { width: inch(8.5), height: inch(3.5) },
    perforationBottom: 0,
  },
  'voucher-top': {
    type: 'top-check',
    paperSize: LETTER,
    rows: 1,
    columns: 1,
    margins: { top: 0, right: 0, bottom: inch(7.5), left: 0 },
    spacing: { horizontal: 0, vertical: 0 },
    checkSize: { width: inch(8.5), height: inch(3.5) },
    perforationBottom: 0,
  },
  'voucher-middle': {
    type: 'middle-check',
    paperSize: LETTER,
    rows: 1,
    columns: 1,
    margins: { top: inch(3.75), right: 0, bottom: inch(3.75), left: 0 },
    spacing: { horizontal: 0, vertical: 0 },
    checkSize: { width: inch(8.5), height: inch(3.5) },
    perforationBottom: 0,
  },
  'voucher-bottom': {
    type: 'bottom-check',
    paperSize: LETTER,
    rows: 1,
    columns: 1,
    margins: { top: inch(7.5), right: 0, bottom: 0, left: 0 },
    spacing: { horizontal: 0, vertical: 0 },
    checkSize: { width: inch(8.5), height: inch(3.5) },
    perforationBottom: 0,
  },
} as const;

export type StockId = keyof typeof Stocks;

export const StockOptions: Array<{ id: StockId; label: string; description: string }> = [
  {
    id: 'business-3up',
    label: '3-per-page (business)',
    description: 'Three 8.5×3.5″ checks stacked on Letter paper.',
  },
  {
    id: 'voucher-top',
    label: 'Voucher · top check',
    description: 'Single check on top with two stubs below.',
  },
  {
    id: 'voucher-middle',
    label: 'Voucher · middle check',
    description: 'Single check between two voucher stubs.',
  },
  {
    id: 'voucher-bottom',
    label: 'Voucher · bottom check',
    description: 'Single check on bottom with stubs above.',
  },
];

let blueprintCounter = 0;
const id = (suffix: string): string => `obj_bp_${suffix}_${(++blueprintCounter).toString(36)}`;

/**
 * Canonical placement of objects on a US business check (ANSI X9.100).
 * Coordinates relative to the check's top-left corner. Width 8.5″ × 3.5″.
 */
function buildStandardObjects(): CanvasObject[] {
  return [
    {
      id: id('company-name'),
      kind: 'text',
      name: 'Company Name',
      position: { x: inch(0.4), y: inch(0.25) },
      size: { width: inch(3.5), height: inch(0.3) },
      rotation: 0,
      locked: false,
      visible: true,
      zIndex: 1,
      value: { kind: 'literal', text: 'Your Company, Inc.' },
      fontFamily: 'Inter',
      fontSize: 14,
      fontWeight: 'bold',
      italic: false,
      underline: false,
      color: '#000000',
      justification: 'left',
      lineHeight: 1.2,
      letterSpacing: 0,
    },
    {
      id: id('company-address'),
      kind: 'text',
      name: 'Company Address',
      position: { x: inch(0.4), y: inch(0.55) },
      size: { width: inch(3.5), height: inch(0.6) },
      rotation: 0,
      locked: false,
      visible: true,
      zIndex: 1,
      value: { kind: 'literal', text: '123 Example St.\nCity, State 00000\n(555) 555-0100' },
      fontFamily: 'Inter',
      fontSize: 9,
      fontWeight: 'regular',
      italic: false,
      underline: false,
      color: '#000000',
      justification: 'left',
      lineHeight: 1.3,
      letterSpacing: 0,
    },
    {
      id: id('bank-name'),
      kind: 'text',
      name: 'Bank Name',
      position: { x: inch(4.4), y: inch(0.25) },
      size: { width: inch(2.5), height: inch(0.3) },
      rotation: 0,
      locked: false,
      visible: true,
      zIndex: 1,
      value: { kind: 'literal', text: 'Bank Name' },
      fontFamily: 'Inter',
      fontSize: 11,
      fontWeight: 'semibold',
      italic: false,
      underline: false,
      color: '#000000',
      justification: 'left',
      lineHeight: 1.2,
      letterSpacing: 0,
    },
    {
      id: id('check-number'),
      kind: 'text',
      name: 'Check Number',
      position: { x: inch(7.0), y: inch(0.25) },
      size: { width: inch(1.3), height: inch(0.3) },
      rotation: 0,
      locked: false,
      visible: true,
      zIndex: 1,
      value: { kind: 'formula', formula: 'LabelField("SerialNumber")' },
      fontFamily: 'Inter',
      fontSize: 14,
      fontWeight: 'bold',
      italic: false,
      underline: false,
      color: '#000000',
      justification: 'right',
      lineHeight: 1.2,
      letterSpacing: 0,
    },
    {
      id: id('date-label'),
      kind: 'text',
      name: 'Date Label',
      position: { x: inch(5.7), y: inch(0.95) },
      size: { width: inch(0.5), height: inch(0.25) },
      rotation: 0,
      locked: false,
      visible: true,
      zIndex: 1,
      value: { kind: 'literal', text: 'DATE' },
      fontFamily: 'Inter',
      fontSize: 8,
      fontWeight: 'medium',
      italic: false,
      underline: false,
      color: '#444444',
      justification: 'left',
      lineHeight: 1.2,
      letterSpacing: 1,
    },
    {
      id: id('date-value'),
      kind: 'text',
      name: 'Date Value',
      position: { x: inch(6.2), y: inch(0.95) },
      size: { width: inch(2.0), height: inch(0.25) },
      rotation: 0,
      locked: false,
      visible: true,
      zIndex: 1,
      value: { kind: 'formula', formula: 'Date()' },
      fontFamily: 'Inter',
      fontSize: 11,
      fontWeight: 'regular',
      italic: false,
      underline: false,
      color: '#000000',
      justification: 'left',
      lineHeight: 1.2,
      letterSpacing: 0,
    },
    {
      id: id('pay-to-label'),
      kind: 'text',
      name: 'Pay To Label',
      position: { x: inch(0.4), y: inch(1.35) },
      size: { width: inch(1.5), height: inch(0.3) },
      rotation: 0,
      locked: false,
      visible: true,
      zIndex: 1,
      value: { kind: 'literal', text: 'PAY TO THE\nORDER OF' },
      fontFamily: 'Inter',
      fontSize: 8,
      fontWeight: 'medium',
      italic: false,
      underline: false,
      color: '#444444',
      justification: 'left',
      lineHeight: 1.2,
      letterSpacing: 1,
    },
    {
      id: id('payee-name'),
      kind: 'text',
      name: 'Payee',
      position: { x: inch(1.6), y: inch(1.4) },
      size: { width: inch(4.6), height: inch(0.3) },
      rotation: 0,
      locked: false,
      visible: true,
      zIndex: 1,
      value: { kind: 'label-field', field: 'Payee' },
      fontFamily: 'Inter',
      fontSize: 13,
      fontWeight: 'regular',
      italic: false,
      underline: false,
      color: '#000000',
      justification: 'left',
      lineHeight: 1.2,
      letterSpacing: 0,
    },
    {
      id: id('amount-box'),
      kind: 'amount-box',
      name: 'Amount Box',
      position: { x: inch(6.4), y: inch(1.4) },
      size: { width: inch(1.7), height: inch(0.35) },
      rotation: 0,
      locked: false,
      visible: true,
      zIndex: 1,
      value: { kind: 'label-field', field: 'Amount' },
      fontFamily: 'Inter',
      fontSize: 14,
      fontWeight: 'bold',
      color: '#000000',
      justification: 'right',
      securityFont: 'amount-protect',
      showCurrencySymbol: true,
    },
    {
      id: id('amount-words'),
      kind: 'text',
      name: 'Amount in Words',
      position: { x: inch(0.4), y: inch(1.85) },
      size: { width: inch(6.2), height: inch(0.3) },
      rotation: 0,
      locked: false,
      visible: true,
      zIndex: 1,
      value: { kind: 'label-field', field: 'AmountWords' },
      fontFamily: 'Inter',
      fontSize: 11,
      fontWeight: 'regular',
      italic: false,
      underline: false,
      color: '#000000',
      justification: 'left',
      lineHeight: 1.2,
      letterSpacing: 0,
    },
    {
      id: id('dollars-label'),
      kind: 'text',
      name: 'Dollars Label',
      position: { x: inch(6.7), y: inch(1.9) },
      size: { width: inch(1.3), height: inch(0.25) },
      rotation: 0,
      locked: false,
      visible: true,
      zIndex: 1,
      value: { kind: 'literal', text: 'DOLLARS' },
      fontFamily: 'Inter',
      fontSize: 9,
      fontWeight: 'medium',
      italic: false,
      underline: false,
      color: '#444444',
      justification: 'right',
      lineHeight: 1.2,
      letterSpacing: 1,
    },
    {
      id: id('memo-label'),
      kind: 'text',
      name: 'Memo Label',
      position: { x: inch(0.4), y: inch(2.6) },
      size: { width: inch(0.5), height: inch(0.25) },
      rotation: 0,
      locked: false,
      visible: true,
      zIndex: 1,
      value: { kind: 'literal', text: 'MEMO' },
      fontFamily: 'Inter',
      fontSize: 8,
      fontWeight: 'medium',
      italic: false,
      underline: false,
      color: '#444444',
      justification: 'left',
      lineHeight: 1.2,
      letterSpacing: 1,
    },
    {
      id: id('memo-value'),
      kind: 'text',
      name: 'Memo',
      position: { x: inch(0.95), y: inch(2.6) },
      size: { width: inch(3.5), height: inch(0.25) },
      rotation: 0,
      locked: false,
      visible: true,
      zIndex: 1,
      value: { kind: 'label-field', field: 'Memo' },
      fontFamily: 'Inter',
      fontSize: 11,
      fontWeight: 'regular',
      italic: false,
      underline: false,
      color: '#000000',
      justification: 'left',
      lineHeight: 1.2,
      letterSpacing: 0,
    },
    {
      id: id('memo-line'),
      kind: 'shape',
      name: 'Memo Line',
      position: { x: inch(0.95), y: inch(2.85) },
      size: { width: inch(3.5), height: 1 },
      rotation: 0,
      locked: false,
      visible: true,
      zIndex: 0,
      shape: 'line',
      strokeColor: '#000000',
      strokeWidth: 1,
      cornerRadius: 0,
    },
    {
      id: id('signature-line'),
      kind: 'shape',
      name: 'Signature Line',
      position: { x: inch(5.0), y: inch(2.85) },
      size: { width: inch(3.0), height: 1 },
      rotation: 0,
      locked: false,
      visible: true,
      zIndex: 0,
      shape: 'line',
      strokeColor: '#000000',
      strokeWidth: 1,
      cornerRadius: 0,
    },
    {
      id: id('micr'),
      kind: 'micr',
      name: 'MICR Line',
      position: { x: inch(0.5), y: inch(3.05) },
      size: { width: inch(7.5), height: inch(0.3) },
      rotation: 0,
      locked: false,
      visible: true,
      zIndex: 5,
      value: { kind: 'literal', text: '' },
      fontVariant: 'e13b',
      fontSize: 12,
      color: '#000000',
      justification: 'left',
    },
  ];
}

const DEFAULT_LABEL_FIELDS: LabelField[] = [
  { name: 'Payee', kind: 'constant', value: '' },
  { name: 'Amount', kind: 'constant', value: '0.00' },
  { name: 'AmountWords', kind: 'constant', value: '' },
  { name: 'Memo', kind: 'constant', value: '' },
  { name: 'SerialNumber', kind: 'incrementing', next: 1001, step: 1, pad: 0 },
];

export function buildBlueprintDocument(stockId: StockId): TemplateDocument {
  return {
    stock: Stocks[stockId] ?? Stocks['business-3up']!,
    objects: buildStandardObjects(),
    labelFields: DEFAULT_LABEL_FIELDS.map((f) => ({ ...f })),
    background: '#ffffff',
  };
}

export function buildSecurityDocument(stockId: StockId): TemplateDocument {
  return {
    stock: Stocks[stockId] ?? Stocks['business-3up']!,
    objects: buildSecurityObjects(),
    labelFields: DEFAULT_LABEL_FIELDS.map((f) => ({ ...f })),
    background: '#ffffff',
  };
}

export function buildBlankDocument(stockId: StockId): TemplateDocument {
  return {
    stock: Stocks[stockId] ?? Stocks['business-3up']!,
    objects: [],
    labelFields: DEFAULT_LABEL_FIELDS.map((f) => ({ ...f })),
    background: '#ffffff',
  };
}

/**
 * Browser-side mirror of `buildSecurityCheckObjects` from
 * `@biz-checks/check-engine`. Produces a fully security-featured 8.5×3.5″
 * business check using primitives only — no new canvas-object kinds. See
 * `packages/check-engine/src/templates/security-objects.ts` for feature
 * documentation. Keep these in sync.
 */
function buildSecurityObjects(): CanvasObject[] {
  const out: CanvasObject[] = [];
  const sid = (suffix: string): string => id(`sec_${suffix}`);

  const microTopBottomText =
    'AUTHORIZED · ORIGINAL DOCUMENT · DO NOT COPY · ' +
    'AUTHORIZED · ORIGINAL DOCUMENT · DO NOT COPY · ' +
    'AUTHORIZED · ORIGINAL DOCUMENT · DO NOT COPY · ' +
    'AUTHORIZED · ORIGINAL DOCUMENT · DO NOT COPY · ' +
    'AUTHORIZED · ORIGINAL DOCUMENT · DO NOT COPY';

  // Pantograph background: 8×5 grid of light-grey rotated "VOID" tiles.
  const pantoCols = 8;
  const pantoRows = 5;
  const pantoCellW = inch(8.5) / pantoCols;
  const pantoCellH = inch(3.5) / pantoRows;
  for (let row = 0; row < pantoRows; row++) {
    for (let col = 0; col < pantoCols; col++) {
      out.push({
        id: sid(`panto_${row}_${col}`),
        kind: 'text',
        name: `Pantograph ${row}.${col}`,
        position: {
          x: col * pantoCellW + pantoCellW * 0.1,
          y: row * pantoCellH + pantoCellH * 0.5,
        },
        size: { width: pantoCellW * 0.9, height: pantoCellH * 0.5 },
        rotation: -22,
        locked: true,
        visible: true,
        zIndex: 0,
        value: { kind: 'literal', text: 'VOID  ORIGINAL  VOID  ORIGINAL' },
        fontFamily: 'Inter',
        fontSize: 9,
        fontWeight: 'bold',
        italic: false,
        underline: false,
        color: '#eef0f3',
        justification: 'left',
        lineHeight: 1.2,
        letterSpacing: 1,
      });
    }
  }

  // Outer + inner security borders.
  out.push({
    id: sid('border_outer'),
    kind: 'shape',
    name: 'Security Border (outer)',
    position: { x: inch(0.08), y: inch(0.08) },
    size: { width: inch(8.5) - inch(0.16), height: inch(3.5) - inch(0.16) },
    rotation: 0,
    locked: true,
    visible: true,
    zIndex: 1,
    shape: 'rectangle',
    strokeColor: '#0e2a4a',
    strokeWidth: 1,
    cornerRadius: 4,
  });
  out.push({
    id: sid('border_inner'),
    kind: 'shape',
    name: 'Security Border (inner)',
    position: { x: inch(0.14), y: inch(0.14) },
    size: { width: inch(8.5) - inch(0.28), height: inch(3.5) - inch(0.28) },
    rotation: 0,
    locked: true,
    visible: true,
    zIndex: 1,
    shape: 'rectangle',
    strokeColor: '#0e2a4a',
    strokeWidth: 0.4,
    cornerRadius: 3,
  });

  // Microprinted top band.
  out.push({
    id: sid('microprint_top'),
    kind: 'text',
    name: 'Microprint (top)',
    position: { x: inch(0.2), y: inch(0.18) },
    size: { width: inch(8.1), height: inch(0.08) },
    rotation: 0,
    locked: true,
    visible: true,
    zIndex: 2,
    value: { kind: 'literal', text: microTopBottomText },
    fontFamily: 'Inter',
    fontSize: 3.6,
    fontWeight: 'regular',
    italic: false,
    underline: false,
    color: '#0e2a4a',
    justification: 'left',
    lineHeight: 1,
    letterSpacing: 0.2,
  });

  // Header block.
  out.push({
    id: sid('company_name'),
    kind: 'text',
    name: 'Company Name',
    position: { x: inch(0.4), y: inch(0.32) },
    size: { width: inch(3.5), height: inch(0.3) },
    rotation: 0,
    locked: false,
    visible: true,
    zIndex: 3,
    value: { kind: 'literal', text: 'Your Company, Inc.' },
    fontFamily: 'Inter',
    fontSize: 14,
    fontWeight: 'bold',
    italic: false,
    underline: false,
    color: '#0e2a4a',
    justification: 'left',
    lineHeight: 1.2,
    letterSpacing: 0,
  });
  out.push({
    id: sid('company_address'),
    kind: 'text',
    name: 'Company Address',
    position: { x: inch(0.4), y: inch(0.62) },
    size: { width: inch(3.5), height: inch(0.6) },
    rotation: 0,
    locked: false,
    visible: true,
    zIndex: 3,
    value: { kind: 'literal', text: '123 Example St.\nCity, State 00000\n(555) 555-0100' },
    fontFamily: 'Inter',
    fontSize: 8.5,
    fontWeight: 'regular',
    italic: false,
    underline: false,
    color: '#333333',
    justification: 'left',
    lineHeight: 1.3,
    letterSpacing: 0,
  });
  out.push({
    id: sid('bank_name'),
    kind: 'text',
    name: 'Bank Name',
    position: { x: inch(4.4), y: inch(0.32) },
    size: { width: inch(2.5), height: inch(0.28) },
    rotation: 0,
    locked: false,
    visible: true,
    zIndex: 3,
    value: { kind: 'literal', text: 'Bank Name, N.A.' },
    fontFamily: 'Inter',
    fontSize: 11,
    fontWeight: 'semibold',
    italic: false,
    underline: false,
    color: '#0e2a4a',
    justification: 'left',
    lineHeight: 1.2,
    letterSpacing: 0,
  });
  out.push({
    id: sid('bank_address'),
    kind: 'text',
    name: 'Bank Address',
    position: { x: inch(4.4), y: inch(0.6) },
    size: { width: inch(2.5), height: inch(0.4) },
    rotation: 0,
    locked: false,
    visible: true,
    zIndex: 3,
    value: { kind: 'literal', text: 'Bank address line 1\nCity, State 00000' },
    fontFamily: 'Inter',
    fontSize: 8.5,
    fontWeight: 'regular',
    italic: false,
    underline: false,
    color: '#333333',
    justification: 'left',
    lineHeight: 1.3,
    letterSpacing: 0,
  });
  out.push({
    id: sid('check_number'),
    kind: 'text',
    name: 'Check Number',
    position: { x: inch(7.0), y: inch(0.32) },
    size: { width: inch(1.3), height: inch(0.3) },
    rotation: 0,
    locked: false,
    visible: true,
    zIndex: 3,
    value: { kind: 'label-field', field: 'SerialNumber' },
    fontFamily: 'Inter',
    fontSize: 14,
    fontWeight: 'bold',
    italic: false,
    underline: false,
    color: '#0e2a4a',
    justification: 'right',
    lineHeight: 1.2,
    letterSpacing: 0,
  });
  out.push({
    id: sid('check_number_label'),
    kind: 'text',
    name: 'Check # Label',
    position: { x: inch(7.0), y: inch(0.6) },
    size: { width: inch(1.3), height: inch(0.18) },
    rotation: 0,
    locked: false,
    visible: true,
    zIndex: 3,
    value: { kind: 'literal', text: 'CHECK NO.' },
    fontFamily: 'Inter',
    fontSize: 7,
    fontWeight: 'medium',
    italic: false,
    underline: false,
    color: '#666666',
    justification: 'right',
    lineHeight: 1.2,
    letterSpacing: 1.5,
  });
  out.push({
    id: sid('stale_date'),
    kind: 'text',
    name: 'Stale-date Warning',
    position: { x: inch(7.0), y: inch(0.78) },
    size: { width: inch(1.3), height: inch(0.16) },
    rotation: 0,
    locked: true,
    visible: true,
    zIndex: 3,
    value: { kind: 'literal', text: 'VOID AFTER 90 DAYS' },
    fontFamily: 'Inter',
    fontSize: 6.5,
    fontWeight: 'bold',
    italic: false,
    underline: false,
    color: '#a31515',
    justification: 'right',
    lineHeight: 1.2,
    letterSpacing: 0.5,
  });

  // Date row.
  out.push({
    id: sid('date_label'),
    kind: 'text',
    name: 'Date Label',
    position: { x: inch(5.7), y: inch(1.05) },
    size: { width: inch(0.5), height: inch(0.22) },
    rotation: 0,
    locked: false,
    visible: true,
    zIndex: 3,
    value: { kind: 'literal', text: 'DATE' },
    fontFamily: 'Inter',
    fontSize: 8,
    fontWeight: 'medium',
    italic: false,
    underline: false,
    color: '#666666',
    justification: 'left',
    lineHeight: 1.2,
    letterSpacing: 1,
  });
  out.push({
    id: sid('date_value'),
    kind: 'text',
    name: 'Date Value',
    position: { x: inch(6.2), y: inch(1.05) },
    size: { width: inch(2.0), height: inch(0.22) },
    rotation: 0,
    locked: false,
    visible: true,
    zIndex: 3,
    value: { kind: 'formula', formula: 'Date()' },
    fontFamily: 'Inter',
    fontSize: 11,
    fontWeight: 'regular',
    italic: false,
    underline: false,
    color: '#000000',
    justification: 'left',
    lineHeight: 1.2,
    letterSpacing: 0,
  });
  out.push({
    id: sid('date_underline'),
    kind: 'shape',
    name: 'Date Underline',
    position: { x: inch(6.2), y: inch(1.27) },
    size: { width: inch(1.85), height: 1 },
    rotation: 0,
    locked: false,
    visible: true,
    zIndex: 2,
    shape: 'line',
    strokeColor: '#666666',
    strokeWidth: 0.5,
    cornerRadius: 0,
  });

  // Pay-to row.
  out.push({
    id: sid('pay_to_label'),
    kind: 'text',
    name: 'Pay To Label',
    position: { x: inch(0.4), y: inch(1.45) },
    size: { width: inch(1.5), height: inch(0.3) },
    rotation: 0,
    locked: false,
    visible: true,
    zIndex: 3,
    value: { kind: 'literal', text: 'PAY TO THE\nORDER OF' },
    fontFamily: 'Inter',
    fontSize: 8,
    fontWeight: 'medium',
    italic: false,
    underline: false,
    color: '#666666',
    justification: 'left',
    lineHeight: 1.2,
    letterSpacing: 1,
  });
  out.push({
    id: sid('payee_name'),
    kind: 'text',
    name: 'Payee',
    position: { x: inch(1.7), y: inch(1.5) },
    size: { width: inch(4.5), height: inch(0.3) },
    rotation: 0,
    locked: false,
    visible: true,
    zIndex: 3,
    value: { kind: 'label-field', field: 'Payee' },
    fontFamily: 'Inter',
    fontSize: 13,
    fontWeight: 'regular',
    italic: false,
    underline: false,
    color: '#000000',
    justification: 'left',
    lineHeight: 1.2,
    letterSpacing: 0,
  });
  out.push({
    id: sid('payee_underline'),
    kind: 'shape',
    name: 'Payee Underline',
    position: { x: inch(1.7), y: inch(1.78) },
    size: { width: inch(4.5), height: 1 },
    rotation: 0,
    locked: false,
    visible: true,
    zIndex: 2,
    shape: 'line',
    strokeColor: '#666666',
    strokeWidth: 0.5,
    cornerRadius: 0,
  });

  // Amount box + box outline.
  out.push({
    id: sid('amount_box'),
    kind: 'amount-box',
    name: 'Amount Box',
    position: { x: inch(6.4), y: inch(1.5) },
    size: { width: inch(1.7), height: inch(0.32) },
    rotation: 0,
    locked: false,
    visible: true,
    zIndex: 3,
    value: { kind: 'label-field', field: 'Amount' },
    fontFamily: 'Inter',
    fontSize: 14,
    fontWeight: 'bold',
    color: '#000000',
    justification: 'right',
    securityFont: 'amount-protect',
    showCurrencySymbol: true,
  });
  out.push({
    id: sid('amount_box_border'),
    kind: 'shape',
    name: 'Amount Box Border',
    position: { x: inch(6.35), y: inch(1.46) },
    size: { width: inch(1.78), height: inch(0.4) },
    rotation: 0,
    locked: false,
    visible: true,
    zIndex: 2,
    shape: 'rectangle',
    strokeColor: '#0e2a4a',
    strokeWidth: 0.5,
    cornerRadius: 2,
  });

  // Written amount line.
  out.push({
    id: sid('amount_words'),
    kind: 'text',
    name: 'Amount in Words',
    position: { x: inch(0.4), y: inch(1.95) },
    size: { width: inch(6.2), height: inch(0.28) },
    rotation: 0,
    locked: false,
    visible: true,
    zIndex: 3,
    value: { kind: 'label-field', field: 'AmountWords' },
    fontFamily: 'Inter',
    fontSize: 11,
    fontWeight: 'regular',
    italic: false,
    underline: false,
    color: '#000000',
    justification: 'left',
    lineHeight: 1.2,
    letterSpacing: 0,
  });
  out.push({
    id: sid('amount_words_underline'),
    kind: 'shape',
    name: 'Amount-Words Underline',
    position: { x: inch(0.4), y: inch(2.23) },
    size: { width: inch(6.2), height: 1 },
    rotation: 0,
    locked: false,
    visible: true,
    zIndex: 2,
    shape: 'line',
    strokeColor: '#666666',
    strokeWidth: 0.5,
    cornerRadius: 0,
  });
  out.push({
    id: sid('dollars_label'),
    kind: 'text',
    name: 'Dollars Label',
    position: { x: inch(6.7), y: inch(1.97) },
    size: { width: inch(1.3), height: inch(0.22) },
    rotation: 0,
    locked: false,
    visible: true,
    zIndex: 3,
    value: { kind: 'literal', text: 'DOLLARS' },
    fontFamily: 'Inter',
    fontSize: 9,
    fontWeight: 'medium',
    italic: false,
    underline: false,
    color: '#666666',
    justification: 'right',
    lineHeight: 1.2,
    letterSpacing: 1,
  });

  // Max-amount notice + security legend.
  out.push({
    id: sid('max_amount_notice'),
    kind: 'text',
    name: 'Max Amount Notice',
    position: { x: inch(0.4), y: inch(2.32) },
    size: { width: inch(4.5), height: inch(0.14) },
    rotation: 0,
    locked: true,
    visible: true,
    zIndex: 3,
    value: { kind: 'literal', text: 'NOT VALID FOR AMOUNTS OVER $50,000.00' },
    fontFamily: 'Inter',
    fontSize: 6.5,
    fontWeight: 'bold',
    italic: false,
    underline: false,
    color: '#a31515',
    justification: 'left',
    lineHeight: 1.2,
    letterSpacing: 0.5,
  });
  out.push({
    id: sid('security_legend'),
    kind: 'text',
    name: 'Security Legend',
    position: { x: inch(0.4), y: inch(2.46) },
    size: { width: inch(4.5), height: inch(0.16) },
    rotation: 0,
    locked: true,
    visible: true,
    zIndex: 3,
    value: {
      kind: 'literal',
      text:
        '\u{1F512}  Microprint border · Pantograph background · ' +
        'Chemically reactive paper · Toner-bonded image · MICR encoded',
    },
    fontFamily: 'Inter',
    fontSize: 5.8,
    fontWeight: 'medium',
    italic: false,
    underline: false,
    color: '#0e2a4a',
    justification: 'left',
    lineHeight: 1.2,
    letterSpacing: 0.2,
  });

  // Memo block.
  out.push({
    id: sid('memo_label'),
    kind: 'text',
    name: 'Memo Label',
    position: { x: inch(0.4), y: inch(2.7) },
    size: { width: inch(0.5), height: inch(0.22) },
    rotation: 0,
    locked: false,
    visible: true,
    zIndex: 3,
    value: { kind: 'literal', text: 'MEMO' },
    fontFamily: 'Inter',
    fontSize: 8,
    fontWeight: 'medium',
    italic: false,
    underline: false,
    color: '#666666',
    justification: 'left',
    lineHeight: 1.2,
    letterSpacing: 1,
  });
  out.push({
    id: sid('memo_value'),
    kind: 'text',
    name: 'Memo',
    position: { x: inch(0.95), y: inch(2.7) },
    size: { width: inch(3.4), height: inch(0.22) },
    rotation: 0,
    locked: false,
    visible: true,
    zIndex: 3,
    value: { kind: 'label-field', field: 'Memo' },
    fontFamily: 'Inter',
    fontSize: 11,
    fontWeight: 'regular',
    italic: false,
    underline: false,
    color: '#000000',
    justification: 'left',
    lineHeight: 1.2,
    letterSpacing: 0,
  });
  out.push({
    id: sid('memo_line_hairline'),
    kind: 'shape',
    name: 'Memo Line (hairline)',
    position: { x: inch(0.95), y: inch(2.94) },
    size: { width: inch(3.4), height: 1 },
    rotation: 0,
    locked: false,
    visible: true,
    zIndex: 2,
    shape: 'line',
    strokeColor: '#666666',
    strokeWidth: 0.5,
    cornerRadius: 0,
  });
  out.push({
    id: sid('memo_microprint'),
    kind: 'text',
    name: 'Memo Microprint',
    position: { x: inch(0.95), y: inch(2.96) },
    size: { width: inch(3.4), height: inch(0.06) },
    rotation: 0,
    locked: true,
    visible: true,
    zIndex: 2,
    value: {
      kind: 'literal',
      text:
        'MEMO · MEMO · MEMO · MEMO · MEMO · MEMO · MEMO · MEMO · MEMO · MEMO · ' +
        'MEMO · MEMO · MEMO · MEMO · MEMO · MEMO · MEMO · MEMO',
    },
    fontFamily: 'Inter',
    fontSize: 3.4,
    fontWeight: 'regular',
    italic: false,
    underline: false,
    color: '#0e2a4a',
    justification: 'left',
    lineHeight: 1,
    letterSpacing: 0.1,
  });

  // Signature line.
  out.push({
    id: sid('sig_line_hairline'),
    kind: 'shape',
    name: 'Signature Line (hairline)',
    position: { x: inch(5.0), y: inch(2.94) },
    size: { width: inch(3.0), height: 1 },
    rotation: 0,
    locked: false,
    visible: true,
    zIndex: 2,
    shape: 'line',
    strokeColor: '#666666',
    strokeWidth: 0.5,
    cornerRadius: 0,
  });
  out.push({
    id: sid('sig_microprint'),
    kind: 'text',
    name: 'Signature Microprint',
    position: { x: inch(5.0), y: inch(2.96) },
    size: { width: inch(3.0), height: inch(0.06) },
    rotation: 0,
    locked: true,
    visible: true,
    zIndex: 2,
    value: {
      kind: 'literal',
      text:
        'AUTHORIZEDSIGNATURE·AUTHORIZEDSIGNATURE·AUTHORIZEDSIGNATURE·' +
        'AUTHORIZEDSIGNATURE·AUTHORIZEDSIGNATURE·AUTHORIZEDSIGNATURE',
    },
    fontFamily: 'Inter',
    fontSize: 3.4,
    fontWeight: 'regular',
    italic: false,
    underline: false,
    color: '#0e2a4a',
    justification: 'left',
    lineHeight: 1,
    letterSpacing: 0.1,
  });
  out.push({
    id: sid('sig_authorization'),
    kind: 'text',
    name: 'Authorized Signature Label',
    position: { x: inch(5.0), y: inch(3.04) },
    size: { width: inch(3.0), height: inch(0.16) },
    rotation: 0,
    locked: false,
    visible: true,
    zIndex: 3,
    value: { kind: 'literal', text: 'AUTHORIZED SIGNATURE' },
    fontFamily: 'Inter',
    fontSize: 7,
    fontWeight: 'medium',
    italic: false,
    underline: false,
    color: '#666666',
    justification: 'center',
    lineHeight: 1.2,
    letterSpacing: 1.5,
  });
  out.push({
    id: sid('two_sig_notice'),
    kind: 'text',
    name: 'Two-Signature Notice',
    position: { x: inch(5.0), y: inch(2.7) },
    size: { width: inch(3.0), height: inch(0.16) },
    rotation: 0,
    locked: true,
    visible: true,
    zIndex: 3,
    value: { kind: 'literal', text: 'TWO SIGNATURES REQUIRED ABOVE $1,000.00' },
    fontFamily: 'Inter',
    fontSize: 6.5,
    fontWeight: 'bold',
    italic: false,
    underline: false,
    color: '#a31515',
    justification: 'center',
    lineHeight: 1.2,
    letterSpacing: 0.5,
  });

  // Bottom microprint band + MICR clear band.
  out.push({
    id: sid('microprint_bottom'),
    kind: 'text',
    name: 'Microprint (bottom)',
    position: { x: inch(0.2), y: inch(3.235) },
    size: { width: inch(8.1), height: inch(0.06) },
    rotation: 0,
    locked: true,
    visible: true,
    zIndex: 2,
    value: { kind: 'literal', text: microTopBottomText },
    fontFamily: 'Inter',
    fontSize: 3.4,
    fontWeight: 'regular',
    italic: false,
    underline: false,
    color: '#0e2a4a',
    justification: 'left',
    lineHeight: 1,
    letterSpacing: 0.2,
  });
  out.push({
    id: sid('micr'),
    kind: 'micr',
    name: 'MICR Line',
    position: { x: inch(0.5), y: inch(3.05) },
    size: { width: inch(7.5), height: inch(0.3) },
    rotation: 0,
    locked: false,
    visible: true,
    zIndex: 5,
    value: { kind: 'literal', text: '' },
    fontVariant: 'e13b',
    fontSize: 12,
    color: '#000000',
    justification: 'left',
  });

  return out;
}
